export {
  createSearchIndexFingerprint,
  ensureSearchIndex,
  finalizeSearchIndexReplacement,
  isSearchIndexCurrent,
  markDirtySearchIndexChapters,
  prepareSearchIndexReplacement,
  querySearchIndex,
  readArchiveIndexSettings,
  readSearchIndexCapabilityStatus,
  readSearchIndexFingerprintFromDatabase,
  readSearchIndexStatus,
  replaceSearchIndex,
  SEARCH_INDEX_FTS_HIT_LIMIT,
  SEARCH_OBJECT_PROPERTY_KIND,
  SEARCH_OBJECT_PROPERTY_OWNER_KIND,
  SINGLE_ARCHIVE_INDEX_ID,
  setFtsIndexEmbedded,
  TEXT_SENTENCE_KIND,
  writeSearchIndexBatch,
} from "./search/index.js";
export type {
  ArchiveIndexSettings,
  SearchIndexInput,
  SearchIndexBuildOptions,
  SearchIndexCapabilityStatus,
  SearchIndexEmbeddingProvider,
  SearchIndexObjectHit,
  SearchIndexProgressEvent,
  SearchIndexProgressPhase,
  SearchIndexProgressReporter,
  SearchIndexQueryResult,
  SearchIndexStatus,
  SearchIndexSelection,
  SearchIndexTextHit,
  SearchIndexWriteCounters,
  SearchObjectPropertyKind,
  SearchObjectPropertyOwnerKind,
  TextSentenceKind,
} from "./search/index.js";
