export enum Language {
  Arabic = "Arabic",
  Danish = "Danish",
  Dutch = "Dutch",
  English = "English",
  Finnish = "Finnish",
  French = "French",
  German = "German",
  Hindi = "Hindi",
  Indonesian = "Indonesian",
  Italian = "Italian",
  Japanese = "Japanese",
  Korean = "Korean",
  Norwegian = "Norwegian",
  Polish = "Polish",
  Portuguese = "Portuguese",
  Russian = "Russian",
  SimplifiedChinese = "Simplified Chinese",
  Spanish = "Spanish",
  Swedish = "Swedish",
  Thai = "Thai",
  TraditionalChinese = "Traditional Chinese",
  Turkish = "Turkish",
  Vietnamese = "Vietnamese",
}
